# Generated by Django 6.0.5 on 2026-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
